### ISSUE TITLE
Invalid composer configuration or misleading documentation

### ISSUE THREAD

**Issue by Bonscho** [deployphp/deployer#1666] opened 2018-08-02 13:53 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Documentation
| Deployer Version  | 6.2.0
| Local Machine OS  | Mac OS X 10.11
| Remote Machine OS | Ubuntu 16.04LTS

### Description 
Misleading or incorrect documentation information about `composer_action` and `composer_options`. 

### Steps to reproduce
My expected behavior is that the following configuration runs composer skipping dev resources and optimizing autoloading. 

### Content of `deploy.php`
```php
set('composer_action', 'install');
set('composer_options', '--optimize-autoloader --no-dev');
```

### Output log
Result is 
`cd /var/www/xxx/releases/17 && /usr/bin/php /var/www/xxx/releases/17/composer.phar --optimize-autoloader --no-dev` 
which is neither expected nor valid. The task exits with a RuntimeException. 

### Workaround
```php
set('composer_action', '');
set('composer_options', 'install --optimize-autoloader --no-dev');
```

works as expected.

**Comment by antonmedv** [comment] 2018-08-02 14:59
Agree, we need to refactor this part of docs or code.

**Comment by syntaxseed** [comment] 2019-05-30 17:35
The problem is that the deploy/vendor.php recipe is missing the composer_action setting when executing composer:

`run('cd {{release_path}} && {{bin/composer}} {{composer_options}}');`

Should be:
`run('cd {{release_path}} && {{bin/composer}} {{composer_action}} {{composer_options}}');`

**Comment by antonmedv** [comment] 2020-04-30 19:49
Fixed in master. Please verify.

**Closed by antonmedv** 2020-04-30 19:49 UTC
Labels: bug, docs needed

**Comment by Bonscho** [comment] 2020-05-01 09:49
Could not verify. After installing deployer from dev-master (upgrading from 6.2.x) I am running into general trouble executing the dep task with following result: 

`vendor/bin/dep deploy test -vv`

```
 Error  in deploy.php on line 54:

  Call to undefined method Deployer\Host\Host::stage()

#0 /var/www/awo-bildungscampus/vendor/deployer/deployer/src/Deployer.php(291): require()
#1 [internal function]: Deployer\Deployer::Deployer\{closure}()
#2 /var/www/awo-bildungscampus/vendor/deployer/deployer/src/Deployer.php(300): call_user_func(Object(Closure))
#3 /var/www/awo-bildungscampus/vendor/deployer/deployer/src/Deployer.php(272): Deployer\Deployer::load('/var/www/awo-bi...')
#4 /var/www/awo-bildungscampus/vendor/deployer/deployer/bin/dep(96): Deployer\Deployer::run('7.0.0-master', '/var/www/awo-bi...')
#5 {main}
```

What is going wrong in here?

**Comment by antonmedv** [comment] 2020-05-01 11:52
There is going to be breaking change. The new version is not support `stage` function.

**Comment by Bonscho** [comment] 2020-05-01 19:07
Then I need some help to migrate from the following syntax to the one required by `dev-master`. It seems to me that more than just the `stage` configuration causes some problems.

```
host('my-hostname.tld')
	->stage('test')
	->roles('frontend')
	->hostname('my-hostname.tld')
	->user('ssh-user')
	->identityFile('path-to-private-ssh-key')
	->set('deploy_path', '/var/www/xxx');
```

**Comment by antonmedv** [comment] 2020-05-02 08:16
I’m in process of writing docs. Basically you now can use set() and set(labels)

**Comment by Bonscho** [comment] 2020-05-02 09:56
Tasks also changed. `cleanup` and `success` are not found. I think before verifying the fix for the above issue, I need to wait for the updated docs to rewrite my whole deploy flow. Could you please drop me line in here after having published the new docs? Thank you for your effort running this project.

**Comment by antonmedv** [comment] 2020-05-02 13:17
Will try to remember. Better follow me on Twitter.
