### ISSUE TITLE
Error on deploy:update_code

### ISSUE THREAD

**Issue by ricardobarantini** [deployphp/deployer#454] opened 2015-09-07 22:43 UTC
I can do deploy with no problems but when I try to update my code with `deploy:update_code` I get this error:

```
[RuntimeException]                              
Unable to login with the provided credentials. 
```

My deployer version is 3.0.10

**Comment by oanhnn** [comment] 2015-09-08 01:41
What provided credentials is you used?

**Comment by ricardobarantini** [comment] 2015-09-08 01:42
SSH key for my private repo in Bitbucket.

**Comment by oanhnn** [comment] 2015-09-08 01:54
This error is throw from [here](https://github.com/deployphp/deployer/blob/master/src/Server/Remote/PhpSecLib.php#L89)
It is you can't access to your server( not Bitbucket ).
Please check your credentials with native `ssh` command.

**Comment by ricardobarantini** [comment] 2015-09-08 02:47
I can connect normally in my server by ssh.

**Comment by oanhnn** [comment] 2015-09-08 02:54
It is maybe problem with key encryption algorithm, it is not support by [`phpseclib` 2.0](https://github.com/phpseclib/phpseclib/releases/tag/2.0.0).
Please try using forward agent to instead of this method.

**Comment by daFish** [comment] 2015-09-08 11:35
This looks like a duplicate of #214.

**Comment by elfet** [comment] 2015-09-10 16:54
We really need to implement native ssh client for Deployer 4.0. I can do it by myself, but it needs time....

**Closed** 2016-03-11 13:02 UTC
Labels: bug
