### ISSUE TITLE
Name or service not known known_hosts with github alias on Deployer v7 rc3

### ISSUE THREAD

**Issue by sts-ryan-holton** [deployphp/deployer#2881] opened 2022-01-05 14:52 UTC
- Deployer version: 7.0.0-rc.3
- Deployment OS: CentOS 7

```php
<?php
namespace Deployer;
use Symfony\Component\Console\Input\InputOption;

require 'recipe/laravel.php';
require 'contrib/npm.php';

// Project repository
set('repository', 'git@github.com:company/fudge-api.git');

// [Optional] Sets the user for the web server.
set('http_user', 'root');

// Shared files/dirs between deploys
add('shared_files', ['.env']);
add('shared_dirs', ['storage', 'vendor', 'node_modules']);

// Set number of releases to keep
set('keep_releases', 3);

// Fudge API (Production)
host('MY_IPV6')
    ->set('labels', ['stage' => 'production'])
    ->set('repository', 'git@MYALIAS:company/fudge-api')
    ->set('branch', 'main')
    ->set('remote_user', 'root')
    ->set('deploy_path', '/var/www/fudge-api');

// Composer install
option('skip-composer', false, InputOption::VALUE_OPTIONAL, 'skip installing composer dependencies');
task('deploy:fudge_api_composer_install', function () {
  $skipComposer = false;
  if (input()->hasOption('skip-composer')) {
    $skipComposer = input()->getOption('skip-composer');
  }
  if (!$skipComposer) {

  } else {
      writeln("<comment>[ skipping Composer ]</comment>");
  }
});

// run custom task
after('deploy:vendors', 'deploy:fudge_api_composer_install');

// [Optional] if deploy fails automatically unlock.
after('deploy:failed', 'deploy:unlock');
```

Fails after `update_code` (see attached), I have multiple Github aliases set up on my server due to multiple projects and ssh keys. This was previously working in Deployer 6.8

![Screenshot 2022-01-05 at 14 51 35](https://user-images.githubusercontent.com/25177538/148237841-336ff662-3981-4430-ba2d-0fa9323a0fd9.png)

**Comment by antonmedv** [comment] 2022-01-10 17:29
Duplicate of #2882

**Closed by antonmedv** 2022-01-10 17:29 UTC
