### ISSUE TITLE
Recipe magento2 - Maintenance check after run would never disable maintenance

### ISSUE THREAD

**Issue by lsv** [deployphp/deployer#2795] opened 2021-11-30 08:17 UTC
- Deployer version: 
master branch (3b0d753)
- Deployment OS:
none

https://github.com/deployphp/deployer/blob/master/recipe/magento2.php#L155-L163

```php
if (!get('maintenance_mode_status_active')) {
            invoke('magento:maintenance:enable');
        }

        run("{{bin/php}} {{release_or_current_path}}/bin/magento setup:upgrade --keep-generated --no-interaction");

        if (!get('maintenance_mode_status_active')) {
            invoke('magento:maintenance:disable');
        }
```

At the first invoke, the maintance status will be updated to TRUE - so the second `!get('maintenance_mode_status_active')` would always return TRUE, and therefor never disable mainteance again.

Same issue https://github.com/deployphp/deployer/blob/master/recipe/magento2.php#L127-L136

And the mainteance status setter

```php
set('maintenance_mode_status_active', function () {
    // detect maintenance mode active
    $maintenanceModeStatusOutput = run("{{bin/php}} {{release_or_current_path}}/bin/magento maintenance:status");
    return strpos($maintenanceModeStatusOutput, MAINTENANCE_MODE_ACTIVE_OUTPUT_MSG) !== false;
});
```

**Comment by peterjaap** [comment] 2021-11-30 10:27
Actually the `maintenance_mode_status_active' bool is only set once, at the start of the recipe; https://github.com/deployphp/deployer/blob/master/recipe/magento2.php#L66

Invoking `magento:maintenance:disable` does *not* set the `maintenance_mode_status_active` as far as I can see. So the second invocation would still return false, thereby disabling maintenance mode again.

**Comment by lsv** [comment] 2021-12-01 09:54
So if you use "get" on a callable function, it will actually not run the callable, just get the "previous" value - That seems odd, from my perspective.

**Comment by antonmedv** [comment] 2021-12-01 10:33
> So if you use "get" on a callable function, it will actually not run the callable, just get the "previous" value - That seems odd, from my perspective.

Yes, this is cache behaviour. And PHP already has feature for returning new value from a callable every time - functions.

**Comment by peterjaap** [comment] 2021-12-02 21:22
Closing this since it's not a bug.

**Closed by peterjaap** 2021-12-02 21:22 UTC
Labels: bug

**Comment by fd-sturniolo** [comment] 2022-05-05 18:39
Actually I'd say it's most definitely a bug. The deploy never actually disables maintenance mode. I had to implement an extra maintenance:disable task after deploy.

I do also think it is very strange that the `set(..., function () {})` syntax doesn't re-call the function on `get()`; why then would you use a function as the parameter instead of calculating the value outside of the `set()` call?
