### ISSUE TITLE
SSH Connection Sharing

### ISSUE THREAD

**Issue by mikeymike** [deployphp/deployer#1164] opened 2017-04-11 14:59 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question, Feature Request
| Deployer Version  | 4.3
| Local Machine OS  | macOS Sierra 10.12.3
| Remote Machine OS | N/A

### Description 
We do deployments through a CI service and use port knocking to allow ssh connections for a brief few seconds. 

Ideally we'd like to be able to share SSH connections across tasks rather than having to do a port knock before every remote task.

I'm not experienced in this but from what I understand Capistrano does this with [connection pooling](https://github.com/capistrano/sshkit#connection-pooling) 

Is this something we can look to add here (if there's not already a way to achieve this)

**Comment by mikeymike** [comment] 2017-04-12 06:24
It seems I've probably misunderstood here as it looks like ssh multiplexing is what is implemented to reuse connections... I'll have to investigate further into why this doesn't seem to be working for us.

**Comment by mikeymike** [comment] 2017-04-12 06:31
It looks like the hardcoded value for the `ControlPersist` is what might be causing our issues. Tasks like local `composer install` and `rsync` etc take much longer than 5 seconds and is probably why the connection can't be reused. 

Would you be open to making this value configurable or indefinite then close on completion / error ?

**Comment by barryvdh** [comment] 2017-04-12 06:45
Isn't it 60 secs on the latest version? https://github.com/deployphp/deployer/blob/9adaa6f72eadff57ec40dbbe972d8cdb1e2112cf/src/Ssh/Client.php#L133
Did you try the 5.0 beta?

**Comment by mikeymike** [comment] 2017-04-12 06:47
I'm not really in a position where using beta tools makes sense unfortunately.... imo it would make sense to have this configurable to suite everyones use case with a sane default... 60s for us is still probably too low with the rsync tasks potentially taking 3-5 minutes.

**Comment by barryvdh** [comment] 2017-04-12 06:50
I understand, but as v5 is changed a lot with multiplexing, and is probably due to release soon. I understand that you can't use beta software in production, but perhaps would be useful to check if the problem is fixed on v5?
See for example this change: https://github.com/deployphp/deployer/commit/7ebe90e9e4b03dcb9ce8225e08e49cb3472f471c

**Comment by mikeymike** [comment] 2017-04-12 06:55
I can definitely take a look and see how it performs but I can be almost certain the timeout will still be too low, (have you ran a composer install on a Magento project 😉 ) especially because the rsync task on average takes over 3 minutes. 

Is there any reason why we shouldn't allow the persist value to be configurable though?

**Comment by antonmedv** [comment] 2017-04-12 07:10
I'll will add options to configure ControlPersist.

**Comment by antonmedv** [comment] 2017-04-12 07:12
#1165

**Closed by antonmedv** 2017-04-12 07:12 UTC
