### ISSUE TITLE
Deal With Jump Servers And Authentication Forwarding 

### ISSUE THREAD

**Issue by markomafs** [deployphp/deployer#223] opened 2015-04-07 22:07 UTC
## What? 
Be able to access a remote server in a VPN throw a (Bastion|Jump) Server
## Why ? 
To access the target servers from my local machine. 
*In my case*, I access a jump server with 
> ssh -A user@jump-host 

Then access all my instances like: ssh host01, ssh host02 , ssh hots03 to make the deployer flow i want. 

**Note**: -A  enable forwarding of the authentication agent connection, that means i don't have my pubKeys at any remote destination server neither a user name or password .

**Comment by elfet** [comment] 2015-04-09 05:34
SSH Forwarding will be in next release. Integration with (Bastion|Jump) Server iа some one make PR.

**Comment by Rylon** [comment] 2015-06-15 14:30
@elfet Hi! Is this feature available in an alpha/beta? I can't get the `git clone` step to work without SSH Agent Forwarding.

When I try to run the same command Deployer is running (which I can see using `-vvv`), but manually via this command `ssh -A user@host "git clone etc"` then it works, so I don't think it's an SSH configuration issue.

My `deploy.php` looks like this:

```php
<?php

// All Deployer recipes are based on `recipe/common.php`.
require 'recipe/composer.php';

// Define a server for deployment.
// Let's name it "prod" and use port 22.
server('prod', 'host', 22)
    ->user('user')
    ->forwardAgent() // You can use identity key, ssh config, or username/password to auth on the server.
    ->stage('production')
    ->env('deploy_path', '/var/www/project_name') // Define the base path to deploy your project to.
    ->env('branch', 'master');

// Specify the repository from which to download your project's code.
// The server needs to have git installed for this to work.
// If you're not using a forward agent, then the server has to be able to clone
// your project from this repository.
set('repository', 'git@github.com:organisation/project_name.git');
```

**Comment by oanhnn** [comment] 2015-06-15 23:56
Did you config your server and your deployment PC to allow forward agent ???
See my comment in issue #232.
Or my example project [oanhnn/deployer-example](https://github.com/oanhnn/deployer-example)

**Comment by Rylon** [comment] 2015-06-16 19:33
Hi @oanhnn yeah it's all configured correctly, I verified by running deployed in verbose mode, then copying those same commands and running them manually using `ssh -A`.

**Comment by oanhnn** [comment] 2015-06-17 01:30
Dear @Rylon ,
If your config is correctly, `ssh` and `ssh -A` is same. Can you try it?
https://github.com/oanhnn/deployer-example/blob/master/docs/enable-feature-ssh-forward-agent.md

**Comment by Rylon** [comment] 2015-06-17 08:01
Hi @oanhnn yes I've tried that as well. All the commands work properly if I run them manually using `ssh user@host "<the command Deployer is running>"`, with or without `-A`.

**Comment by kbsali** [comment] 2015-07-13 15:30
Same here! :(

**Comment by elfet** [comment] 2015-07-14 12:14
Look like your a init in another way. Sorry can tell why to has this problems. I can't reproduce it.

**Comment by kbsali** [comment] 2015-07-14 14:52
Ok, let me try to help in debugging/fixing that.

Here is what I'm trying to do :

```php
<?php

require 'recipe/symfony.php';

server('production', 'server.com', 22)
    ->user('kevin')
    ->forwardAgent()
    ->stage('production')
    ->env('deploy_path', '/var/www/download.blabla.com')
;
set('repository', 'git@bitbucket.org:bleeee/download.blabla.com.git');
```

I've raised the ssh LogLevel on the server to DEBUG2 to get extra info and here is what happens :

With Deployer:
```
kevin@ks:~/workspace/test/test-deployer$ deployer.phar deploy production -vv
➤ Executing task deploy:prepare
⤷ on [production]
Run: echo $0
Run: if [ ! -d /var/www/download.blabla.com ]; then echo ""; fi
Run: cd /var/www/download.blabla.com && if [ ! -d releases ]; then mkdir releases; fi
Run: cd /var/www/download.blabla.com && if [ ! -d shared ]; then mkdir shared; fi
⤶ done on [production]
✔ Ok
➤ Executing task deploy:release
⤷ on [production]
Run: date +%Y%m%d%H%M%S
Run: mkdir /var/www/download.blabla.com/releases/20150714143351
Run: cd /var/www/download.blabla.com && if [ -h release ]; then rm release; fi
Run: ln -s /var/www/download.blabla.com/releases/20150714143351 /var/www/download.blabla.com/release
⤶ done on [production]
✔ Ok
➤ Executing task deploy:update_code
⤷ on [production]
Run: readlink /var/www/download.blabla.com/release
Run: git clone  --depth 1 --recursive -q git@bitbucket.org:bleeee/download.blabla.com.git /var/www/download.blabla.com/releases/20150714143351 2>&1


  [RuntimeException]
  debug2: ssh_connect: needpriv 0
  debug1: Connecting to bitbucket.org [131.103.20.167] port 22.
  debug1: Connection established.
  ...
  debug1: SSH2_MSG_SERVICE_ACCEPT received
  debug2: key: /home/kevin/.ssh/id_rsa ((nil)
  debug2: key: /home/kevin/.ssh/id_dsa ((nil)
  debug2: key: /home/kevin/.ssh/id_ecdsa ((nil)
  debug2: key: /home/kevin/.ssh/id_ed25519 ((nil)
  debug1: Authentications that can continue: publickey
  debug1: Next authentication method: publickey
  debug1: Trying private key: /home/kevin/.ssh/id_rsa
  debug1: Trying private key: /home/kevin/.ssh/id_dsa
  debug1: Trying private key: /home/kevin/.ssh/id_ecdsa
  debug1: Trying private key: /home/kevin/.ssh/id_ed25519
  debug2: we did not send a packet, disable method
  debug1: No more authentication methods to try.
  Permission denied (publickey)
  fatal: Could not read from remote repository.
  Please make sure you have the correct access rights
  and the repository exists.
```

Very same command but directly from the command line :
```
kevin@ks:~/workspace/test/test-deployer$ ssh -A server.com "git clone  --depth 1 --recursive -q git@bitbucket.org:bleeee/download.blabla.com.git /var/www/download.blabla.com/releases/20150714143351 2>&1"
debug2: ssh_connect: needpriv 0
debug1: Connecting to bitbucket.org [131.103.20.168] port 22.
debug1: Connection established.
...
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug2: key: /home/kevin/.ssh/id_rsa (0x7fa7bc9350b0),
debug2: key: /home/kevin/.ssh/id_rsa ((nil)),
debug2: key: /home/kevin/.ssh/id_dsa ((nil)),
debug2: key: /home/kevin/.ssh/id_ecdsa ((nil)),
debug2: key: /home/kevin/.ssh/id_ed25519 ((nil)),
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/kevin/.ssh/id_rsa
debug2: we sent a publickey packet, wait for reply
debug1: Remote: Forced command: conq username:kbsali
...
```

See how with deployer i'm getting :
    debug2: key: /home/kevin/.ssh/id_rsa ((nil)
while with ssh command :
    debug2: key: /home/kevin/.ssh/id_rsa (0x7fa7bc9350b0)

To me that's where Deployer is failing... it is not properly forwarding the agent.

Hope this helps.
Thx

**Comment by kbsali** [comment] 2015-07-14 17:07
as a work around i set the repo with my credentials :
```php
set('repository', 'https://username:pwd@bitbucket.org:bleeee/download.blabla.com.git');
```
But that's not idea as it can not be commited to our repo.

**Comment by Rylon** [comment] 2015-07-14 17:29
Thanks for that example @kbsali, that's exactly the same behaviour I'm seeing here also.

**Closed** 2015-08-21 07:33 UTC
Labels: feature

**Comment by VivekShingala** [comment] 2022-03-21 04:06
Hi,

Looks like deploying through bastion server is fixed by using native ssh in v4. Could you please provide any example on how to configure the host in case of bastion server? That would be really helpful.
