### ISSUE TITLE
Autoloading problem

### ISSUE THREAD

**Issue by loevgaard** [deployphp/deployer#3598] opened 2023-05-16 18:29 UTC
Could we reopen this issue? https://github.com/deployphp/deployer/issues/3485

Thanks in advance.

**Comment by antonmedv** [comment] 2023-05-16 21:24
Sure, please summarize the issue.

**Comment by antonmedv** [comment] 2023-05-23 13:19
Sure. Created a new issues

**Comment by antonmedv** [comment] 2023-05-23 13:19
Duplicate of https://github.com/deployphp/deployer/issues/3605

**Closed by antonmedv** 2023-05-23 13:19 UTC
