### ISSUE TITLE
Warning: Identity file id_rsa not accessible: No such file or directory.

### ISSUE THREAD

**Issue by pascal08** [deployphp/deployer#1507] opened 2018-01-18 14:18 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Question
| Deployer Version  | 6.0.3
| Local Machine OS  | Ubuntu 16.04
| Remote Machine OS | Ubuntu 16.04

### Description 
Somehow my deployer setup is broken. I get the follow warning in all commands involving establishing a ssh-connection with one of my servers. It doesn't matter which server I'm deploying to, this message pops up everywhere in the logs.
```
Warning: Identity file /home/user/.ssh/id_rsa not accessible
```

Using the following command I'm log in perfectly fine into my servers:
```
ssh user@xxx
```

On a side-note: I'm using Docker for running PHP. 

### Steps to reproduce
I really have no clue.

### Content of `hosts.yml`
```
.deploy-template: &deploy-template
    ssh_type: native
    ssh_multiplexing: true

    user: xxx
    port: 22
    identityFile: /home/user/.ssh/id_rsa

staging:
  <<: *deploy-template
  hostname: xxx
  stage: staging
  deploy_path: /var/www/staging
```

### Output log
```
[localhost] > git rev-parse --abbrev-ref HEAD
[localhost] < master
✈︎ Deploying master on xxx
• done on [staging]
➤ Executing task deploy:prepare
[staging] > echo $0
[staging] < ssh multiplexing initialization
[staging] < Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-109-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

[staging] < Warning: Identity file /home/user/.ssh/id_rsa not accessible: No such file or directory.
[staging] < bash
[staging] > if [ ! -d /var/www/staging ]; then mkdir -p /var/www/staging; fi
[staging] < Warning: Identity file /home/user/.ssh/id_rsa not accessible: No such file or directory.
[staging] > if [ ! -L /var/www/staging/current ] && [ -d /var/www/staging/current ]; then echo 'true'; fi
[staging] < Warning: Identity file /home/user/.ssh/id_rsa not accessible: No such file or directory.
[staging] > cd /var/www/staging && if [ ! -d .dep ]; then mkdir .dep; fi
[staging] < Warning: Identity file /home/user/.ssh/id_rsa not accessible: No such file or directory.
[staging] > cd /var/www/staging && if [ ! -d releases ]; then mkdir releases; fi
[staging] < Warning: Identity file /home/user/.ssh/id_rsa not accessible: No such file or directory.
[staging] > cd /var/www/staging && if [ ! -d shared ]; then mkdir shared; fi
[staging] < Warning: Identity file /home/user/.ssh/id_rsa not accessible: No such file or directory.
```

**Comment by antonmedv** [comment] 2018-01-18 14:54
Check if local user which perfoms deploy can access /home/user/.ssh/id_rsa.

**Comment by pascal08** [comment] 2018-01-18 15:05
```
user@xxx:~$ ls -la /home/user/.ssh/id_rsa
-rw------- 1 user user 1679 Jan 18 14:03 /home/user/.ssh/id_rsa
```

I can not imagine it has something to do with server-side configuration since all my servers have this problem now. But then, still, I do not understand why it can not access this file.

**Comment by staabm** [comment] 2018-01-18 15:08
I guess the deploy process does not run with your current user.
you might check with "whoami" from within the deploy process.

**Comment by pascal08** [comment] 2018-01-18 15:13
@staabm 

```
deployer run whoami --hosts staging -vvv
```


```
[staging] > whoami
[staging] < ssh multiplexing initialization
[staging] < Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-109-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

[staging] < Warning: Identity file /home/user/.ssh/id_rsa not accessible: No such file or directory.
[staging] < user
```

**Comment by pascal08** [comment] 2018-01-18 15:17
The weird thing is that I can see from the logs that it can establish the ssh connection. No deployer settings were changed between the time my deployments worked fine and now. Same goes for all my servers except one which I migrated to another hosting provider yesterday. I have not updated deployer, changed ssh-keys or whatsoever.

**Comment by antonmedv** [comment] 2018-01-18 15:23
Indeed, this is really strange behavior. Will be cool to try to run ssh comand what deployer runs exactly. But It's difficult, need to put echo in deployer (Will do it by default for -vvv in v7).

**Comment by pascal08** [comment] 2018-01-18 15:32
@antonmedv 
I think that a really nice feature. Looking forward to that.

More information on this problem: it can not be a problem caused by my docker setup, since executing deployer using php without docker reports the same warning (Identity file not accessible).

**Comment by antonmedv** [comment] 2018-01-18 15:34
Can't tell why. Try to implement pseudo-deployer command. Try run this: https://gist.github.com/antonmedv/53181dce02a876872e74cb56c9090c62

But patch for you host, etc.

**Comment by pascal08** [comment] 2018-01-18 15:38
```
1:ssh -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux_*host* *host*  'bash -s'
1:run 'pwd'
1:/home/localosuser
1:command returned 0
2:ssh -O check -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_mux_*host*  *host* 2>&1
2:run ''
2:Master running (pid=29330)
2:command returned 0
```

**Comment by antonmedv** [comment] 2018-01-18 15:45
Strange, can't tell what's broken.

**Comment by pascal08** [comment] 2018-01-18 16:02
Sadly, turning multiplexing off doesn't fix it either. 

Just upgraded to v6.0.5. No luck. 

I will be looking further into this tomorrow. I'll keep you posted. Thanks for the help so far! Greatly appreciated.

**Comment by awsdevopro** [comment] 2018-06-29 17:32
I have faced same issue when transferring file. 

ssh -i ~/.ssh/key.pem source_dir destination_dir
ssh -i $HOME/.ssh/key.pem source_dir destination_dir

I changed "~" to "$HOME" and it worked perfectly. 

Thanks

**Comment by gargharshal** [comment] 2021-07-12 06:50
What if the path contains a space, in that we have to use quotes.
Instead of `C:/Users/Username/filename.pem`, we have this `C:/Users/User name/filename.pem`. In the later case the quotes are must.

**Comment by schmengler** [comment] 2021-07-12 07:36
Not sure if it's the same on Windows, but you can also escape spaces instead: `C:/Users/User\ name/filename.pem`

**Comment by antonmedv** [comment] 2021-09-18 13:35
Duplicate of #2612

**Closed by antonmedv** 2021-09-18 13:35 UTC

**Comment by ekpono** [comment] 2022-01-10 09:20
What worked for me is that the I had to manually type the quote instead of just pasting it
