### ISSUE TITLE
Is there a max time for a task to execute?

### ISSUE THREAD

**Issue by svycka** [deployphp/deployer#1316] opened 2017-08-02 07:09 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question
| Deployer Version  | v5.1.3
| Local Machine OS  | Ubuntu
| Remote Machine OS | Ubuntu

### Description 
I was deploying and db migration task took longer than 300 seconds. I am not 100% sure this is not doctrine-migrations problem but when I run it on remote machine locally migration worked. If this is default limit how can I configure this?

### Output log
```
[Symfony\Component\Process\Exception\ProcessTimedOutException]
    The process "ssh -A -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=~/.ssh/deployer_xx@xx.lt xx@xx.lt  'bash -s; printf "[exit_code:%s]" $?;  
    '" exceeded the timeout of 300 seconds.
```

**Comment by antonmedv** [comment] 2017-08-03 10:37
Duplicate of #1256

**Closed by antonmedv** 2017-08-03 10:37 UTC
