### ISSUE TITLE
Cannot deploy from working directory with space in path name

### ISSUE THREAD

**Issue by Bilge** [deployphp/deployer#2450] opened 2021-03-09 19:24 UTC
- Deployer version: v7.0.0-beta.13
- Deployment OS: Linux 4.4.0-18362-Microsoft (WSL)

When the current working directory contains a space in the path name (e.g. `/mnt/c/Foo Bar`), deploy fails during connection with:

>In Master.php line 165:

>  Could not open input file: /mnt/c/Foo

This was not an issue with version 6.8.x.

Moreover, if PHP binary itself is on a path with a space in the filename, it will fail in a similar fashion but with slightly different output. For example, when PHP is installed at `c:\prog\PHP 8.0`, deploy fails with:

>'C:\prog\PHP' is not recognized as an internal or external command,
operable program or batch file.
>In Master.php line 165:

>  [Deployer\Exception\ConnectException]

Again, this is a v7 exclusive regression.

**Comment by antonmedv** [comment] 2021-03-09 19:37
This is definitely a bug 🐛 
Lets find a root cause.

**Comment by Bilge** [comment] 2021-03-09 19:46
Most likely there is some quoting/escaping issue.

**Comment by antonmedv** [comment] 2021-03-09 20:10
Yes, this is the place.

**Comment by Bilge** [comment] 2021-03-09 20:36
I think the fundamental problem is this library makes the error of calling `Process::fromShellCommandline()`, which is an insecure variant of the constructor style command line assembly which requires passing the command line as an array of the command arguments, e.g. `new Process(['foo', 'bar'])`. When the arguments are passed as an array, the Process library internally manages escaping of the arguments (by calling `Process::escapeArgument`) so that any such spaces should become a non-issue.

**Comment by antonmedv** [comment] 2021-03-10 12:03
This will may work, but we need a way to split command from run() func to arguments.

**Comment by antonmedv** [comment] 2021-03-13 20:55
I think I fixed it, please verify.
 
See https://github.com/deployphp/deployer/pull/2458

**Comment by Bilge** [comment] 2021-03-17 17:55
It seems not much has changed.

>deployer/deployer                     v7.0.0-beta.16            Deployment Tool

>bilge@localhost:/mnt/c/Foo Bar$ deploy
>Could not open input file: /mnt/c/Foo
task deploy:failed
Could not open input file: /mnt/c/Foo

**Comment by Bilge** [comment] 2021-05-03 14:32
What happened to this?

**Comment by antonmedv** [comment] 2021-05-03 16:41
What happened?

**Comment by Bilge** [comment] 2021-05-20 00:14
Any update on this?

**Comment by Bilge** [comment] 2021-07-13 14:47
Do I need to try to fix this one myself?

**Comment by Bilge** [comment] 2021-07-13 22:59
Well I "fixed" the issue, but I can't really test it fully because more things are broken. For some reason, `deploy:prepare` task does a lot more than it used to, and makes a lot more faulty assumptions by trying to run `deploy:update_code` even though I don't want to do this because I deploy artifacts instead of abusing git as a deploy tool.

**Comment by Bilge** [comment] 2021-07-13 23:49
Pretty sure I have this working now, but again I hit another roadblock as the `write()` function was removed? Why?

**Comment by antonmedv** [comment] 2021-09-19 15:38
Fixed in f3152a5264d0fd96316ff4ad5a01cb3024710907

**Closed by antonmedv** 2021-09-19 15:38 UTC
Labels: bug, v7
