### ISSUE TITLE
deployer 7.0.2 does not run with php 8.2

### ISSUE THREAD

**Issue by chenrui333** [deployphp/deployer#3399] opened 2022-12-08 16:12 UTC
- Deployer version: 7.0.2
- Deployment OS: macOS

      Please, provide a minimal reproducible example of deploy.php

## How to reproduce

- Install php8.2
- Install deployer 7.0.2
- Run `dep init --no-interaction`

```
==> /opt/homebrew/Cellar/deployer/7.0.2/bin/dep init --no-interaction
Last 15 lines from /Users/rui/Library/Logs/Homebrew/deployer/test.01.dep:
2022-12-08 11:07:16 -0500

/opt/homebrew/Cellar/deployer/7.0.2/bin/dep
init
--no-interaction

 ErrorException  in DumpCompletionCommand.php on line 48:

  Using ${var} in strings is deprecated, use {$var} instead
```

relates to https://github.com/Homebrew/homebrew-core/pull/117647

**Comment by neverlose-lv** [comment] 2022-12-11 10:10
Same here

**Comment by Schrank** [comment] 2022-12-11 10:24
Have you turned on deprecation warnings? What happens if you turn them off?

Or in other words: Is the problem PHP or the error handler?

**Comment by neverlose-lv** [comment] 2022-12-11 11:06
> Have you turned on deprecation warnings? What happens if you turn them off?
> 
> Or in other words: Is the problem PHP or the error handler?

Don't mess up. It is not a deprecation warning. It is a deprecated syntax/approach in the new version of PHP 8.2., e.g. -> you are not allowed to do 'so' anymore in the new version.

**Comment by sgrossberndt** [comment] 2022-12-12 13:10
I am running deployer in a composer image

I had to add `echo 'error_reporting=8191' >> /usr/local/etc/php/php-cli.ini` in order to fix it:
```
    - composer global require deployer/deployer $COMPOSER_OPTIONS
    # Workaround for https://github.com/deployphp/deployer/issues/3399
    - echo 'error_reporting=8191' >> /usr/local/etc/php/php-cli.ini
    - /tmp/vendor/bin/dep deploy -vvv ${TARGET_HOSTS}
```

Really a pity such a thing makes deployments fail :-(
I think, I'll keep this setting even when the symfony/console issue is solved.

**Comment by Schrank** [comment] 2022-12-12 14:01
It should, because PHP 8.2 deprecated it only. It isn't removed.

https://www.php.net/releases/8.2/en.php
> # Deprecations and backward compatibility breaks
> - Deprecated ${} string interpolation.

Can you try with error_reporting=0 please? 🤔

**Comment by sgrossberndt** [comment] 2022-12-12 14:05
Works for me as well without modifying php.ini:

```
user@host:~# docker run -it composer:2.3.10 /bin/bash
6495b430254d:/app# composer global require deployer/deployer
Changed current directory to /tmp
Info from https://repo.packagist.org: #StandWithUkraine
Using version ^7.0 for deployer/deployer
./composer.json has been created
Running composer update deployer/deployer
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking deployer/deployer (v7.0.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading deployer/deployer (v7.0.2)
  - Installing deployer/deployer (v7.0.2): Extracting archive
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
6495b430254d:/app# /tmp/vendor/bin/dep
 ErrorException  in DumpCompletionCommand.php on line 48:

  Using ${var} in strings is deprecated, use {$var} instead

6495b430254d:/app# php -d error_reporting=8191 /tmp/vendor/bin/dep
Deployer 7.0.2

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi|--no-ansi  Force (or disable --no-ansi) ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -f, --file=FILE       Recipe file path
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  blackjack    Play blackjack
  completion   Dump the shell completion script
  config       Get all configuration options for hosts
  help         Display help for a command
  init         Initialize deployer in your project
  list         List commands
  run          Run any arbitrary command on hosts
  self-update  Updates deployer.phar to the latest version
  ssh          Connect to host through ssh
  tree         Display the task-tree for a given task
```

**Comment by sgrossberndt** [comment] 2022-12-12 14:31
I can confirm running `php -d error_reporting=8191 bin/dep` does not work for a complete deployment.
I guess this is because deployer internally calls `bin/dep` again and there the parameter is missing? That might explain why my solution editing the php.ini works.

**Comment by neverlose-lv** [comment] 2022-12-13 07:26
The deployer code should be rewritten without deprecated syntax, instead of suppressing the deprecation warnings. Because deprecated syntax will be removed in future versions at all + you probably may suppress other deprecation warnings, that are not related with the deployer.

**Comment by Schrank** [comment] 2022-12-13 08:14
Agree, but deprecations are warnings. Warnings which say: You have now 3 years to fix your code. So we are happy to get less expectations and more cooperation in form of a PR :-) Deployer will work with 8.0.2 and with PHP 9, but not today and tomorrow without deprecation warnings.

**Comment by sgrossberndt** [comment] 2022-12-13 08:54
Deployer requires an outdated [version v5.4.5 of `symfony/console` in composer.lock](https://github.com/deployphp/deployer/blob/master/composer.lock#L1086). This version of `symfony/console` contains the deprecated syntax, not deployer itself.
Doing a `composer upgrade` for `symfony/console` should suffice to fix this, as [deployer 5.4.9](https://github.com/symfony/console/releases/tag/v5.4.9) (which was already released on 2022-05-27 by the way) [fixes this](https://github.com/symfony/console/commit/06974380c667d7d8e3cd0f24bf51f816a71ca6c6), as pointed out already by @thommyhh in https://github.com/deployphp/deployer/issues/3399#issuecomment-1346193419

**Comment by Konafets** [comment] 2022-12-13 13:32
There was a PR (now closes and not merged) to bump the symfony/console. https://github.com/deployphp/deployer/pull/3280

**Closed** 2023-01-09 09:25 UTC

**Comment by jasperf** [comment] 2023-02-07 07:28
Same issue just now post `brew update`. Tried `composer update deployer/deployer` but had 

```
composer update deployer/deployer
Loading composer repositories with package information
Updating dependencies                                 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mpociot/vat-calculator is locked to version 3.1.0 and an update of this package was not requested.
    - mpociot/vat-calculator 3.1.0 requires php ^7.3|~8.0.0|~8.1.0 -> your php version (8.2.2) does not satisfy that requirement.
  Problem 2
    - laminas/laminas-code 4.6.0 requires php >=7.4, <8.2 -> your php version (8.2.2) does not satisfy that requirement.
    - bensampo/laravel-enum v6.0.0 requires laminas/laminas-code ^3.4 || ^4 -> satisfiable by laminas/laminas-code[4.6.0].
    - bensampo/laravel-enum is locked to version v6.0.0 and an update of this package was not requested.
```

Checking for solutions now.

**Comment by maxhelias** [comment] 2023-02-07 08:05
@jasperf 

> Problem 1

Your version of mpociot/vat-calculator is not compatible with php 8.2

> Problem 2

 Your version of laminas/laminas-code is not compatible with php 8.2

You should update your dependencies also with the -W option of composer or refer to the rigth project
