### ISSUE TITLE
Nested Task Listener Not Work

### ISSUE THREAD

**Issue by ihsanudin** [deployphp/deployer#565] opened 2016-02-22 07:51 UTC
Example:
 I have 3 main task

* doA
* doB
* doC

And then i add task listener to doA (ex: before) with name:

* doAa

And then i add task listener to doAa (ex: after) with name:

* doAaA

The result is the task doAaA is never execute

**Comment by nemoinho** [comment] 2016-03-10 21:29
So basically you have a recipe like this?

    <?php
    require_once __DIR__ . '/recipe/common.php';

    task('A', function(){echo 'A';});
    task('B', function(){echo 'B';});
    task('C', function(){echo 'C';});
    task('A:before', function(){echo 'A:before';});
    before('A', 'A:before');
    task('A:before:after', function(){echo 'A:before:after';});
    after('A:before', 'A:before:after');

    task('deploy', [
        'A',    
        'B',    
        'C',    
    ])->desc('Task order demo');

**Comment by ihsanudin** [comment] 2016-03-11 02:25
@nemoinho : may be like that. I use symfony recipe with nested callback/event

**Comment by elfet** [comment] 2016-03-11 06:11
`A:before:after`?

**Comment by nemoinho** [comment] 2016-03-11 09:25
@elfet Just a name for me to find it, with a very simple rule after the colon follows the position (before / after) to the initially task. If more than one addition have the same position I set also a incremental suffix. The colon can also be replace by a underscore or something it doesn't matter in my case.

But anyway @ihsanudin this test runs well for me, therefore I asked you if it looks similar, maybe you can provide your definition of tasks and dependencies in the order as noted in your recipe, so I can understand your problem better

**Comment by ihsanudin** [comment] 2016-03-11 09:49
@nemoinho : i was remove the task, but when i try your deploy script, all task is running well. May be it's my mistake, could i close this issue?

**Comment by nemoinho** [comment] 2016-03-11 17:51
In my opinion yes, because if it really was a bug than it will occurs another time and someone will report the issue may or may not with a full explanation. But if it was not a bug and you don't close the issue it may says for a really long time, because no one knows the status and waste time by figuring out whats going on.

**Closed** 2016-03-12 03:23 UTC
Labels: bug
