### ISSUE TITLE
Deployer\Collection\Collection::get(): Argument #1 ($name) must be of type string, null given

### ISSUE THREAD

**Issue by thiagolcks** [deployphp/deployer#3410] opened 2022-12-15 23:36 UTC
- Deployer version: v7.0.0-rc4
- Deployment OS: macOs

Today, entirely out of the blue, after I've done some deploys, I started to get this error:
Deployer\Collection\Collection::get(): Argument #1 ($name) must be of type string, null given, called in phar:///Users/me/Sites/mine/my-project/vendor/deployer/dist/dep/src/Executor/Server.php on line 89

It was first happening in the deploy:vendors step, and now in the deploy:release step.

I checked the git, and I didn't change the deploy.php. Try to debug the error but couldn't figure out the reason for the Server.php

Anybody else having similar issues?

**Comment by Schrank** [comment] 2022-12-15 23:43
May it be, that you changed for some reason the PHP version on the server or locally? Recently PHP7.4 got out of support, so maybe your hosting provider did it?

**Comment by thiagolcks** [comment] 2022-12-15 23:44
I'm using PHP 8.1

**Comment by thiagolcks** [comment] 2022-12-16 01:48
I've tried to deploy it to another folder, and it worked. It's not making any sense.

**Comment by thiagolcks** [comment] 2022-12-16 02:09
I've just solved the issue by deleting the folder .dep from the server. Then I deleted the older folders from the releases folder.

What happened? I have no clue, and the error message does not seem to be related with the problem.

**Comment by Schrank** [comment] 2022-12-16 08:50
Sounds like a super interesting bug, no one has time to investigate? I'll close the issue, because it doesn't seem reproducible. If you have more infos, please tell us, so someone can fix it!

**Closed by Schrank** 2022-12-16 08:50 UTC

**Comment by antonmedv** [comment] 2022-12-16 11:59
@Schrank thanks for cleaning up 🧹👍🏻

**Comment by oxyc** [comment] 2023-06-09 22:50
Seeing this as well, both deploying using GitHub actions and macOS. It happens at varying steps of the deploy for me too.

Using PHP 8.0.28.

Stacktrace:

```
#0 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/deployer/deployer/src/Executor/Server.php(89): Deployer\Collection\Collection->get(NULL)
#1 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/deployer/deployer/src/Executor/Server.php(62): Deployer\Executor\Server->router(Object(React\Http\Message\ServerRequest))
#2 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/MiddlewareRunner.php(49): Deployer\Executor\Server->Deployer\Executor\{closure}(Object(React\Http\Message\ServerRequest))
#3 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/MiddlewareRunner.php(54): React\Http\Io\MiddlewareRunner->call(Object(React\Http\Message\ServerRequest), 2)
#4 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Middleware/RequestBodyParserMiddleware.php(34): React\Http\Io\MiddlewareRunner->React\Http\Io\{closure}(Object(React\Http\Message\ServerRequest))
#5 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/MiddlewareRunner.php(59): React\Http\Middleware\RequestBodyParserMiddleware->__invoke(Object(React\Http\Message\ServerRequest), Object(Closure))
#6 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/MiddlewareRunner.php(54): React\Http\Io\MiddlewareRunner->call(Object(React\Http\Message\ServerRequest), 1)
#7 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Middleware/RequestBodyBufferMiddleware.php(63): React\Http\Io\MiddlewareRunner->React\Http\Io\{closure}(Object(React\Http\Message\ServerRequest))
#8 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/promise/src/FulfilledPromise.php(28): React\Http\Middleware\RequestBodyBufferMiddleware->React\Http\Middleware\{closure}(NULL)
#9 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/promise/src/Promise.php(134): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#10 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#11 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#12 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/promise-stream/src/functions.php(144): React\Promise\Promise::React\Promise\{closure}(NULL)
#13 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Promise\Stream\{closure}()
#14 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/HttpBodyStream.php(80): Evenement\EventEmitter->emit('close')
#15 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/HttpBodyStream.php(179): React\Http\Io\HttpBodyStream->close()
#16 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\HttpBodyStream->handleEnd()
#17 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/LengthLimitedStream.php(87): Evenement\EventEmitter->emit('end')
#18 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\LengthLimitedStream->handleData('ild_path": "\\/t...')
#19 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/http/src/Io/CloseProtectionStream.php(96): Evenement\EventEmitter->emit('data', Array)
#20 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Http\Io\CloseProtectionStream->handleData('ild_path": "\\/t...')
#21 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#22 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('ild_path": "\\/t...')
#23 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit('data', Array)
#24 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData(Resource id #390)
#25 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity(14601)
#26 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/deployer/deployer/src/Executor/Master.php(242): React\EventLoop\StreamSelectLoop->run()
#27 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/deployer/deployer/src/Executor/Master.php(134): Deployer\Executor\Master->runTask(Object(Deployer\Task\Task), Array)
#28 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/deployer/deployer/src/Command/MainCommand.php(136): Deployer\Executor\Master->run(Array, Array, NULL)
#29 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/symfony/console/Command/Command.php(298): Deployer\Command\MainCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#30 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#31 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(Deployer\Command\MainCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#32 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/deployer/deployer/src/Deployer.php(320): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/deployer/deployer/bin/dep(98): Deployer\Deployer::run('7.0.0-master', '/Users/oskarsch...')
#35 /Users/oskarscholdstrom/Projects/Genero/suomentyokalu/vendor/bin/dep(120): include('/Users/oskarsch...')
#36 {main}
```

**Comment by mohamedds-12** [comment] 2023-12-21 08:53
> I've just solved the issue by deleting the folder .dep from the server. Then I deleted the older folders from the releases folder.
> 
> What happened? I have no clue, and the error message does not seem to be related with the problem.

Worked for me after deleting the .dep folder from the server as @thiagolcks mentioned.

**Comment by thiagolcks** [comment] 2024-01-29 13:27
It happened again here, I'm coming back to see how I solved it the last time  😁

**Comment by mohamedds-12** [comment] 2024-01-29 16:48
> > I've just solved the issue by deleting the folder .dep from the server. Then I deleted the older folders from the releases folder.
> > What happened? I have no clue, and the error message does not seem to be related with the problem.
> 
> Worked for me after deleting the .dep folder from the server as @thiagolcks mentioned, I think I agree with @oxyc that it could be related to the release_log file having too much lines.

It's definitely it, happend again twice and the commo. Thing is that the file was over 300... the only solution we found is to creat a cron job on the server to watch th release_log file so it doesn't go over 300... So far so good.
