### ISSUE TITLE
deploy:symlink warning on localhost() (using bash syntax with sh)

### ISSUE THREAD

**Issue by cronfy** [deployphp/deployer#1258] opened 2017-06-10 10:41 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0.3
| Local Machine OS  | Linux Mit 17.3
| Remote Machine OS | N/A

I get warning from `deploy:symlink` when deploying to localhost:

```
$ dep -vvv deploy local
...
➤ Executing task deploy:symlink
[localhost] > if [[ $(man mv 2>&1 || mv -h 2>&1 || mv --help 2>&1) =~ '--no-target-directory' ]]; then echo 'true'; fi
[localhost] < sh: 1: [[: not found
...
```

Looks like is it trying to use `sh`, but command has `bash` syntax `[[`.

Deployer config:

```
<?php
namespace Deployer;

require 'recipe/yii.php';

set('repository', 'git@gitlab.com:my/repo.git');
set('git_tty', true); // [Optional] Allocate tty for git on first deployment
add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

localhost()
    ->stage('local')
    ->set('deploy_path', '/var/www/_build')
;
    
after('deploy:failed', 'deploy:unlock');
```

**Comment by antonmedv** [comment] 2017-06-10 13:05
Try run it from bash shell.

**Comment by cronfy** [comment] 2017-06-10 13:09
My local shell is bash. This command works if I run it directly:

```
$ echo $0
-bash
$ if [[ $(man mv 2>&1 || mv -h 2>&1 || mv --help 2>&1) =~ '--no-target-directory' ]]; then echo 'true'; fi
true
```

I am running deployer right from this bash shell.

But `dep -vvv deploy local` shows warning, as I showed it the issue.

**Comment by antonmedv** [comment] 2017-06-19 14:25
Closing as not active issue.

**Comment by cronfy** [comment] 2017-06-19 14:29
Why not active? I answered to your comment. Any more information I can provide?

**Comment by antonmedv** [comment] 2017-06-19 14:31
Sorry, my mistake.  Try running it from bash session.

**Comment by cronfy** [comment] 2017-06-19 14:34
I am running it from bash session, as I wrote here: https://github.com/deployphp/deployer/issues/1258#issuecomment-307564159

**Comment by antonmedv** [comment] 2017-06-19 14:35
Okay. When there no way to run it from non-bash shell. Use bash. :)

**Closed by antonmedv** 2017-06-19 14:35 UTC

**Comment by cronfy** [comment] 2017-06-19 14:42
**I am USING bash and I see this warning**

It appears twice, here is a log:

```
$ echo $0
-bash
cronfy@layoone /var/www $ dep -vvv deploy local
➤ Executing task deploy:prepare
...
➤ Executing task deploy:lock
...
➤ Executing task deploy:release
...
[localhost] > cd /var/www/_build && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[localhost] < sh: 1: [[: not found
...
➤ Executing task deploy:update_code
...
➤ Executing task lik:warm_vendor
...
➤ Executing task deploy:vendors
...
➤ Executing task deploy:symlink
[localhost] > if [[ $(man mv 2>&1 || mv -h 2>&1 || mv --help 2>&1) =~ '--no-target-directory' ]]; then echo 'true'; fi
[localhost] < sh: 1: [[: not found
...
➤ Executing task deploy:unlock
...
➤ Executing task cleanup
...
➤ Executing task success
✔ Ok [0ms]
Successfully deployed!
```

**Comment by Konrad90** [comment] 2018-01-30 14:34
related issue https://github.com/deployphp/deployer/issues/1373

**Comment by staabm** [comment] 2018-01-30 14:44
another duplicate of the same issue is https://github.com/deployphp/deployer/issues/1445

**Comment by lepiklepik** [comment] 2021-03-18 11:49
The same issue on Debian 10.8. CLI is Bash.

**Comment by antonmedv** [comment] 2021-03-18 13:03
What is your local shell?

**Comment by lepiklepik** [comment] 2021-03-18 13:35
/bin/bash 
I've even tried to alias sh='/bin/bash'

**Comment by antonmedv** [comment] 2021-03-18 13:39
If you run bash as ‘sh’ it will start with —posix mode. Try running it from new bash session.

**Comment by lepiklepik** [comment] 2021-03-18 13:41
I've tried everything. New bash session, aliases, new bash session inside current bash session, etc.:)
Still getting sh: 1: [[: not found

**Comment by antonmedv** [comment] 2021-03-18 13:43
What bash version?

**Comment by lepiklepik** [comment] 2021-03-18 13:44
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)

**Comment by antonmedv** [comment] 2021-03-18 13:57
Try to simulate same with symfony process component. Create a php file, new process from command line with [[ in it. Will it work?

**Comment by lepiklepik** [comment] 2021-03-18 15:11
Not sure how to correctly use [[ ]] with Symfony Process, but the following code returns an error.

$process = Process::fromShellCommandline("[[ 'test' == 'test' ]]");
$process->run();

Error Output:
================
sh: 1: [[: not found
 in /home/aaa/index.php:14
Stack trace:
#0 {main}
  thrown in /home/aaa/index.php on line 14

Behaviour is the same on both local and remote hosts.
If I run [[ 'test' == 'test' ]] from cmd - it works.

**Comment by antonmedv** [comment] 2021-03-18 15:15
So problem with 

$process = Process::fromShellCommandline("[[ 'test' == 'test' ]]");
$process->run();

It works for me. Please, investigate why it not working properly.

**Comment by lepiklepik** [comment] 2021-03-18 15:24
echo shell_exec("[[ 'test' == 'test' ]]");

returns the same error

**Comment by lepiklepik** [comment] 2021-03-20 19:33
Update:
echo shell_exec("[[ 'test' == 'test' ]]"); - works on Centos and doesn't work on Debian based distros.

**Comment by antonmedv** [comment] 2021-03-20 20:58
This is really strange. Maybe even some related bug in php.

**Comment by staabm** [comment] 2021-03-20 21:11
@lepiklepik could you double check whether this differs between php versions?

**Comment by lepiklepik** [comment] 2021-03-21 18:28
I've found the answer.

PHP exec() uses /bin/dash on Debian-based distros and /bin/bash on Centos. And there is no easy way to change that.

Here is a simple command that outputs the current cli intrepreter: echo shell_exec("ls -l /proc/$$/exe | sed 's%.*/%%'");

So, it seems, the only way to fix the issue is to explicitly run /bin/bash -c "command" in the Deployer's code.

**Comment by antonmedv** [comment] 2021-03-21 19:12
Awesome, thanks for debugging. Actually we can use as default for runLocally.  Same as for ssh client.

**Comment by lepiklepik** [comment] 2021-03-21 20:11
As a quick workaround, I've created the following function in 6.8.0

```
function testWithBash($command)
{
    return run("/bin/bash -c \"if $command; then echo 'true'; fi\"") === 'true';
}
```

and use it in

```
function commandSupportsOption($command, $option)
{
    return testWithBash("[[ $(man $command 2>&1 || $command -h 2>&1 || $command --help 2>&1) =~ '$option' ]]");
}
```
