### ISSUE TITLE
filters (onRoles, onHost, etc..) don't seem to work on a task group

### ISSUE THREAD

**Issue by BillyMorgan** [deployphp/deployer#1319] opened 2017-08-06 02:39 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug ... I think
| Deployer Version  | N/A
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
I'm not sure if this is a bug, sure feels like it to me though!

### Steps to reproduce
1) Add ->onRoles (or similar) filter to a group of tasks
2) The task runs on all the hosts, not only the hosts that apply to the defined filter

### Content of `deploy.php`
```php
<?php
namespace Deployer;

require_once 'recipe/common.php';

host('localhost')
    ->roles('group1')
    ->set('deploy_path', '/tmp/deployer');

host('remote-server')
    ->roles('group2')
    ->set('deploy_path', '/tmp/deployer');

desc('Just group1');
task('deploy', [
    'deploy:prepare',
    'deploy:lock',
    'deploy:release',
    'deploy:shared',
    'deploy:writable',
    'deploy:clear_paths',
    'deploy:symlink',
    'deploy:unlock',
    'cleanup',
    'success'
])->onRoles('group1');
```

### Output log
➤ Executing task deploy:prepare
[localhost] > echo $0
[localhost] > if [ ! -d /tmp/deployer ]; then mkdir -p /tmp/deployer; fi
[localhost] > if [ ! -L /tmp/deployer/current ] && [ -d /tmp/deployer/current ]; then echo true; fi
[localhost] > cd /tmp/deployer && if [ ! -d .dep ]; then mkdir .dep; fi
[localhost] > cd /tmp/deployer && if [ ! -d releases ]; then mkdir releases; fi
[localhost] > cd /tmp/deployer && if [ ! -d shared ]; then mkdir shared; fi
• done on [localhost]
[remote-server] > echo $0
[remote-server] > if [ ! -d /tmp/deployer ]; then mkdir -p /tmp/deployer; fi
[remote-server] > if [ ! -L /tmp/deployer/current ] && [ -d /tmp/deployer/current ]; then echo true; fi
[remote-server] > cd /tmp/deployer && if [ ! -d .dep ]; then mkdir .dep; fi
[remote-server] > cd /tmp/deployer && if [ ! -d releases ]; then mkdir releases; fi
[remote-server] > cd /tmp/deployer && if [ ! -d shared ]; then mkdir shared; fi
• done on [remote-server]
✔ Ok [194ms]
➤ Executing task deploy:lock
[localhost] > if [ -f /tmp/deployer/.dep/deploy.lock ]; then echo 'true'; fi
[localhost] > touch /tmp/deployer/.dep/deploy.lock
• done on [localhost]
[remote-server] > if [ -f /tmp/deployer/.dep/deploy.lock ]; then echo 'true'; fi
[remote-server] > touch /tmp/deployer/.dep/deploy.lock
• done on [remote-server]
✔ Ok [61ms]
➤ Executing task deploy:release
[localhost] > cd /tmp/deployer && (if [ -h release ]; then echo 'true'; fi)
[localhost] > cd /tmp/deployer && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[localhost] > cd /tmp/deployer && (cd releases && ls -t -1 -d */)
[localhost] > cd /tmp/deployer && (if [ -f .dep/releases ]; then echo "true"; fi)
[localhost] > cd /tmp/deployer && (tail -n 15 .dep/releases)
[localhost] > cd /tmp/deployer && (if [ -d /tmp/deployer/releases/3 ]; then echo 'true'; fi)
[localhost] > cd /tmp/deployer && (date +"%Y%m%d%H%M%S")
[localhost] > cd /tmp/deployer && (echo '20170806143146,3' >> .dep/releases)
[localhost] > cd /tmp/deployer && (mkdir /tmp/deployer/releases/3)
[localhost] > cd /tmp/deployer && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[localhost] > cd /tmp/deployer && (ln -nfs --relative /tmp/deployer/releases/3 /tmp/deployer/release)
• done on [localhost]
[remote-server] > cd /tmp/deployer && (if [ -h release ]; then echo 'true'; fi)
[remote-server] > cd /tmp/deployer && ([ -d releases ] && [ "$(ls -A releases)" ] && echo "true" || echo "false")
[remote-server] > cd /tmp/deployer && (cd releases && ls -t -1 -d */)
[remote-server] > cd /tmp/deployer && (if [ -f .dep/releases ]; then echo "true"; fi)
[remote-server] > cd /tmp/deployer && (tail -n 15 .dep/releases)
[remote-server] > cd /tmp/deployer && (if [ -d /tmp/deployer/releases/3 ]; then echo 'true'; fi)
[remote-server] > cd /tmp/deployer && (date +"%Y%m%d%H%M%S")
[remote-server] > cd /tmp/deployer && (echo '20170806143146,3' >> .dep/releases)
[remote-server] > cd /tmp/deployer && (mkdir /tmp/deployer/releases/3)
[remote-server] > cd /tmp/deployer && (if [[ $(man ln 2>&1 || ln -h 2>&1 || ln --help 2>&1) =~ '--relative' ]]; then echo 'true'; fi)
[remote-server] > cd /tmp/deployer && (ln -nfs --relative /tmp/deployer/releases/3 /tmp/deployer/release)
• done on [remote-server]
✔ Ok [413ms]
➤ Executing task deploy:shared
• done on [localhost]
• done on [remote-server]
✔ Ok [0ms]
➤ Executing task deploy:writable
• done on [localhost]
• done on [remote-server]
✔ Ok [1ms]
➤ Executing task deploy:clear_paths
• done on [localhost]
• done on [remote-server]
✔ Ok [0ms]
➤ Executing task deploy:symlink
[localhost] > if [[ $(man mv 2>&1 || mv -h 2>&1 || mv --help 2>&1) =~ '--no-target-directory' ]]; then echo 'true'; fi
[localhost] > mv -T /tmp/deployer/release /tmp/deployer/current
• done on [localhost]
[remote-server] > if [[ $(man mv 2>&1 || mv -h 2>&1 || mv --help 2>&1) =~ '--no-target-directory' ]]; then echo 'true'; fi
[remote-server] > mv -T /tmp/deployer/release /tmp/deployer/current
• done on [remote-server]
✔ Ok [147ms]
➤ Executing task deploy:unlock
[localhost] > rm -f /tmp/deployer/.dep/deploy.lock
• done on [localhost]
[remote-server] > rm -f /tmp/deployer/.dep/deploy.lock
• done on [remote-server]
✔ Ok [42ms]
➤ Executing task cleanup
[localhost] > cd /tmp/deployer && if [ -e release ]; then  rm release; fi
[localhost] > cd /tmp/deployer && if [ -h release ]; then  rm release; fi
• done on [localhost]
[remote-server] > cd /tmp/deployer && if [ -e release ]; then  rm release; fi
[remote-server] > cd /tmp/deployer && if [ -h release ]; then  rm release; fi
• done on [remote-server]
✔ Ok [70ms]
➤ Executing task success
✔ Ok [0ms]
Successfully deployed!

**Comment by dautushenka** [comment] 2017-08-07 09:04
Duplicate of #1313

**Closed** 2017-08-07 09:05 UTC
Labels: bug, good for beginner
