### ISSUE TITLE
Run optional commands with option flags

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1124] opened 2017-03-22 21:49 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        |  Feature Request
| Deployer Version  | 5.x
| Local Machine OS  | N/A
| Remote Machine OS | N/A

### Description 
When deploying, sometime you might want different behaviour. In case of Laravel, you might want to usually not run migrations, but add a flag to do so. Eg. when running:

```sh
dep deploy --migrate
```

I'd like to add `artisan:migrate` before `deploy:symlink`. 
This could be similar for other commands (eg. extra steps that not always are needed)

### Possible solutions
I guess this would be possible be adding a call to `argument`, but this is not easily done in the array with all commands. Perhaps something like:

```php
desc('Execute optional commands');
task('deploy:options', function () {
    if (input()->hasOption('migrate')) {
        run('artisan:migrate');
    }
});
option('migrate', null, null, 'Execute artisan migrate');
```

But more elegant would be something like:
```php
optionalBefore('deploy:symlink', 'artisan:migrate', 'migrate'); 
```

**Comment by antonmedv** [comment] 2017-03-26 06:36
Duplicate of #851

**Closed by antonmedv** 2017-03-26 06:36 UTC

**Comment by barryvdh** [comment] 2017-03-26 06:40
Thats about config settings, not command line flags, is it? 
Although we could use a flag to enable/disable a setting perhaps.

**Comment by antonmedv** [comment] 2017-03-26 06:42
`option('migrate', null, null, 'Execute artisan migrate');` ?
