### ISSUE TITLE
git_clone_dissociate doesn't work in Deployer v7

### ISSUE THREAD

**Issue by sbrow** [deployphp/deployer#2598] opened 2021-07-02 13:59 UTC
- Deployer version: Deployer 7.0.0-beta.23
- Deployment OS: Homestead v12.3.0 | Settler v11.3.0 | Ubuntu 20.04

I may be an idiot, but certain config options aren't working for me.

deploy.yaml
```yaml
import:
    - recipe/laravel.php

config:
  application: 'example'
  repository: 'https://github.com/laravel/laravel'

  # If yes, removes git information after cloning.
  # broken?
  git_clone_dissociate: no

  # Skip deployment if no changes have been pushed.
  # broken?  
  check_remote_head: yes

hosts:
  localhost:
    deploy_path: '~/{{application}}'

#tasks:

after:
  deploy:failed: deploy:unlock

```

**Comment by antonmedv** [comment] 2021-07-02 14:29
In Deployer v7 got archive is used.

**Comment by codedge** [comment] 2021-08-08 13:14
I use [Statamics Git Integration](https://statamic.dev/git-integration) which relies on having the `.git` information withing the working directory.
It would be greate to have a working configuration - also for Deployer v7 - to choose if the `.git` directory should be removed from the working dir or not... as it was for version 6.

Right now when using Statamic _with Git integration_ we are stuck with v6 of Deployer.

**Comment by antonmedv** [comment] 2021-09-23 17:15
Duplicate of #2616

**Closed by antonmedv** 2021-09-23 17:15 UTC
