### ISSUE TITLE
[7.0-beta] Aliases don't work as expected

### ISSUE THREAD

**Issue by bpolaszek** [deployphp/deployer#2528] opened 2021-04-27 15:09 UTC
- Deployer version: 7.0.beta-23

Hello there,
It looks like we can't ssh to a specific host with its label anymore.

Example: `deploy.php`:

```php
namespace Deployer;

$foo = host('127.0.0.1');
$foo->set('alias', 'example.com');

$bar = host('127.0.0.2');
$bar->set('alias', 'example.org');
```

<img width="755" alt="Capture d’écran 2021-04-27 à 17 06 22" src="https://user-images.githubusercontent.com/5569077/116264857-e97c0580-a77a-11eb-9ffc-4c53b6785d10.png">

Running `php vendor/bin/dep ssh 127.0.0.1` works, but:
- It requires to know the server's IP
- Sometimes you just don't know it (I dynamically fetch a list of servers matching a specific tag, from DigitalOcean API, for instance)
- It used to work in 6.8.

Thank you,
Ben

**Comment by bpolaszek** [comment] 2021-06-01 12:48
Hello there,

Any news on this?

Thank you,
Ben

**Comment by Schrank** [comment] 2021-06-01 12:59
Hey @bpolaszek, thanks for your question! If there is news, one of us will happily write it down here to keep you updated.

This is an open source project, therefore you have three options:
- be patient
- fix it yourself
- offer motivation (feel free to ask here for someone to fix it for you)

**Comment by bpolaszek** [comment] 2021-06-02 07:49
Hello @Schrank,

I know this is open-source and I am an open-source maintainer and contributor myself.

But this package has over 6M+ downloads and is kinda widely used. 

Problem is, PHP 8 has been out for more than 6 months and the only replacement for stable 6.8 (not PHP8-compatible, plus `deployer/recipes` has been set read-only so it will never be) is a beta version with major API and human/computer interactions changes, tons of bugs, and no documentation. 

So I'd really like to help, but I don't even know what direction you are currently following, and why everything suddenly got overly complicated (setting a stage on a host, targeting a stage during deployment, etc).

So I think I'll opt for the 1st option, and probably downgrade to 6.x, by relying on `6.x-dev` branch to have PHP8 minimal support + copy/paste recipes. Which is, let's face it, just a huge regression for a tool of such quality 🙂 

Thank you,
Ben

**Comment by antonmedv** [comment] 2021-06-03 16:20
This is disappointing. In v7 tremendous amount of effort was put. It have lots, lots of improvements, bug fixes and rethinking of concepts for better dev experience. Yes it still lacks docs, but I think at this point most of bugs was fixed by our community.

**Comment by TheFakeCake** [comment] 2021-09-24 14:41
Hello,

I'm looking at the issue and it seems the SshCommand doesn't retrieve the selected host by its alias.
It uses the `get` method from `HostCollection` and, correct me if I'm wrong, but I suspect the keys in the collection are the hostnames given to the `Host` constructor.

https://github.com/deployphp/deployer/blob/b724073157c5d78d8a4cb1348221c8eef56b7943/src/Command/SshCommand.php#L50
https://github.com/deployphp/deployer/blob/b724073157c5d78d8a4cb1348221c8eef56b7943/src/Command/SshCommand.php#L76

I will make a PR.

As a workaround, you can try to define your hosts like this :
```php
namespace Deployer;

$foo = host('example.com');
$foo->setHostname('127.0.0.1');

$bar = host('example.org');
$bar->setHostname('127.0.0.2');
```

**Comment by antonmedv** [comment] 2021-09-26 08:30
Actually solution is not right. In HostCollection hosts stored by alias.
```php
host('prod')->setHostname('127.0.0.1');
host('beta')->setHostname('127.0.0.2');
```

```
$ dep ssh prod
```

Works as intended. 

But if you change the alias after the host is added to HostCollection - the key is not updated in HostCollection.

So two options:
- Update HostCollection key on alias update.
- Disallow alias updates.

**Closed** 2021-09-26 08:31 UTC
Labels: bug, v7
