### ISSUE TITLE
Provision: err sudo: a terminal is required to read the password

### ISSUE THREAD

**Issue by underdpt** [deployphp/deployer#2953] opened 2022-02-08 10:04 UTC
- Deployer version: 7.0.0-rc4
- Deployment OS: Ubuntu 20.04

```php
host('my-host.com')
    ->set('labels', ['stage' => 'production'])
    ->set('branch', 'master')
    ->set('remote_user', 'mainsip')
    ->set('become', 'root')
    ->set('port', 22)
    ->set('deploy_path', '/var/www/my-host.com');
```

When trying to provision on a new server I get the error:

```sh
task provision:website
[my-host.com]  error  in website.php on line 16:
[my-host.com] run [ -d /var/www/my-host.com ] || mkdir /var/www/my-host.com
[my-host.com] err sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
[my-host.com] exit code -1 (Unknown error)
```

This seems to be related to #2939, but running

```sh
❯ .\vendor\bin\dep provision -o remote_user=root
```

produces the error:

```sh
task provision:website
[my-host.com]  error  in website.php on line 16:
[my-host.com] run [ -d /var/www/my-host.com ] || mkdir /var/www/my-host.com
[my-host.com] err mkdir: cannot create directory ‘/var/www/my-host.com’: No such file or directory
[my-host.com] exit code 1 (General error)
```

This could be solved by adding the option `-p` to `mkdir`, but if I manually create `/var/www`  and run the provision as root:

```sh
task provision:website
[my-host.com]  error  in website.php on line 16:
[my-host.com] run [ -d /var/www/my-host.com ] || mkdir /var/www/my-host.com
[my-host.com] err mkdir: cannot create directory ‘/var/www/my-host.com’: Permission denied
[my-host.com] exit code 1 (General error)
```

**Comment by antonmedv** [comment] 2022-02-08 13:29
>     ->set('remote_user', 'mainsip')
>     ->set('become', 'root')

Looks like your mainsip can't become root user without the password. 

> err mkdir: cannot create directory ‘/var/www/my-host.com’: Permission denied

This is strange, root user should have all permissions. Looks like this was ran not under root.

**Comment by antonmedv** [comment] 2022-02-08 14:25
Yes, run dep with -vvv option and see exact command what was executed there.

**Comment by underdpt** [comment] 2022-02-15 16:51
This is what I get (removing options `remote_user` and `become` from `deploy.php`):

```sh
❯ .\vendor\bin\dep provision:website -o remote_user=root -vvv
task provision:website
[my-host.com] c:\php\php.exe D:\desarrollos\davanni\inicia\web\vendor\deployer\deployer\bin\dep worker --port 51115 --task provision:website --host my-host.com --option remote_user=root --decorated -vvv
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": 8b36520784fed0ea722d; bash -ls"
[my-host.com] run [ -d /var/www/gastos ] || mkdir /var/www/gastos
[my-host.com] mkdir: cannot create directory ‘/var/www/gastos’: No such file or directory
[my-host.com]  error  in website.php on line 16:
[my-host.com] exit code 1 (General error)
```

This is in a new host, `root` user created, enabled and can login with a ssh key. 

If I manually create `/var/www`:

```sh
❯ .\vendor\bin\dep provision:website -o remote_user=root -vvv
task provision:website
[my-host.com] c:\php\php.exe D:\desarrollos\davanni\inicia\web\vendor\deployer\deployer\bin\dep worker --port 51142 --task provision:website --host my-host.com --option remote_user=root --decorated -vvv
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": 1e237cbbc5ba7753f325; bash -ls"
[my-host.com] run [ -d /var/www/gastos ] || mkdir /var/www/gastos
[my-host.com] mkdir: cannot create directory ‘/var/www/gastos’: Permission denied
[my-host.com]  error  in website.php on line 16:
[my-host.com] exit code 1 (General error)
```

I have to manually create `/var/www` and change permissions to `drwxrwxrwx` for this to work as expected:

```sh
❯ .\vendor\bin\dep provision:website -o remote_user=root -vvv
task provision:website
[my-host.com] c:\php\php.exe D:\desarrollos\davanni\inicia\web\vendor\deployer\deployer\bin\dep worker --port 64154 --task provision:website --host my-host.com --option remote_user=root --decorated -vvv
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": 70ce43dd327f7530f4b5; bash -ls"
[my-host.com] run [ -d /var/www/gastos ] || mkdir /var/www/gastos
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": af57470df7ee68bab2cf; bash -ls"
[my-host.com] run realpath /var/www/gastos
[my-host.com] /var/www/gastos
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": 9270a74a35fc0c6b8b9f; bash -ls"
[my-host.com] run cd /var/www/gastos && ([ -d log ] || mkdir log)
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": 32e820d1436b0e75b223; bash -ls"
[my-host.com] run cd /var/www/gastos && (chgrp caddy log)
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": c411530a3134ec9b53da; bash -ls"
[my-host.com] run cd /var/www/gastos && (if [ -f Caddyfile ]; then echo +true; fi)
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": b5ff14b5f07496bcead5; bash -ls"
[my-host.com] run cd /var/www/gastos && (echo $'gastos.iniciasoluciones.es

root * /var/www/gastos/current/public
file_server
php_fastcgi * unix//run/php/php8.1-fpm.sock {
        resolve_root_symlink
}

log {
        output file /var/www/gastos/log/access.log
}

handle_errors {
        @404 {
                expression {http.error.status_code} == 404
        }
        rewrite @404 /404.html
        file_server {
                root /var/dep/html
        }
}' > Caddyfile)
[my-host.com] ssh "-p" "22" "-A" "deployer@my-host.com" ": c608daa8121c7cd1e785; bash -ls"
[my-host.com] run cd /var/www/gastos && (caddy reload)
[my-host.com] {"level":"info","ts":1644943615.57891,"msg":"using adjacent Caddyfile"}
[my-host.com] info Website gastos.iniciasoluciones.es configured!
done on my-host.com
done provision:website 7s 851ms
```

So it seems that `website` recipe is missing privileges elevation somewhere, and it should create the destination dir with all parents (`mkdir -p`).

**Comment by antonmedv** [comment] 2022-03-17 19:19
So, the problem is with call:
```
ssh 'deployer@demo.deployer.org' 'sudo -H -u root bash -ls'
```
If you can become root without password - there is no problem. Otherwise Deployer can't ask you the password here.

**Comment by underdpt** [comment] 2022-03-18 06:41
Yes, I can become root without password (all the previous tasks work as expected), so I think the issue is elsewhere.

I think mkdir should use `sudo` and also create all the parent directories if missing with `-p`.

Thanks!

**Comment by antonmedv** [comment] 2022-03-18 07:14
Let’s close this issue for now. Feel free to create new one.

**Closed by antonmedv** 2022-03-18 07:14 UTC
Labels: minor bug

**Comment by Kaos-Industries** [comment] 2022-03-26 22:36
> > ```
> > ->set('remote_user', 'mainsip')
> > ->set('become', 'root')
> > ```
> 
> Looks like your mainsip can't become root user without the password.
> 
> > err mkdir: cannot create directory ‘/var/www/my-host.com’: Permission denied
> 
> This is strange, root user should have all permissions. Looks like this was ran not under root.

Is it necessary for the deployer user to always be root?

**Comment by antonmedv** [comment] 2022-03-26 22:57
No

**Comment by facundopereztomasek** [comment] 2022-11-17 00:07
This is not a minor bug, the provision:website routine is not working out of the box, as it is expected.
This bug stops all the provision command.
