### ISSUE TITLE
make some ssh tasks on remote server and copy few folders from remote to webserver

### ISSUE THREAD

**Issue by familyman-131** [deployphp/deployer#1523] opened 2018-01-26 09:58 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug, Question
| Deployer Version  | 6.0.5
| PHP Version  | 7.0.17
| Local Machine OS  | Ubuntu 14.04.5 LTS
| Remote Machine OS | Ubuntu 16.04.3 LTS

### Description
i need to make some tasks on remote server and copy few folders from remote to webserver  
i start deployer tasks directly on webserver
it looks like ssh command on webserver in the deployer task, after connect to remote server triyng to start script on webserver again, not command in .sh script 
(use just "date" command for debug)

### Steps to reproduce
create task with ssh command on remote server (direct ssh user@remoteserver "date" or in .sh script)
check if ssh command works without deployer 
**./gulp.sh**
_Птн Янв 26 11:33:17 EET 2018_
**ssh user@remoteserver "date"**
_Птн Янв 26 11:34:23 EET 2018_

run 
**/opt/php70/bin/php /usr/local/bin/dep --file=/var/www/...../deploy.test.php dev_gulp -vvv**

### partial content of `deploy.php`
```php
host('remoteserver')
    ->user('user');
    set('deploy_path', '~/www/');
    set('StrictHostKeyChecking', 'no');
...
desc('make gulp on dev');
task('dev_gulp', function () {
    //run('/bin/bash /var/www/..../gulp.sh');
    //run('/var/www/..../gulp.sh');
    //run('ssh user@remoteserver "date"');
});

```

### content of `gulp.sh`
```php
#!/bin/bash
/usr/bin/ssh user@remoteserver 'date'

```

### Output log if i use .sh in deployer
➤ Executing task dev_gulp
[remoteserver] > /var/www/..../gulp.sh
[remoteserver] < ssh multiplexing initialization
[remoteserver] < Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-109-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Может быть обновлён 1 пакет.
0 обновлений касаются безопасности системы.

*** Требуется перезагрузка системы ***
You have new mail.

[remoteserver] < bash: line 1: /var/www/..../gulp.sh: No such file or directory
PHP Warning:  pcntl_fork() has been disabled for security reasons in phar:///usr/local/bin/dep/src/Utility/Reporter.php on line 22

  [Deployer\Exception\RuntimeException (127)]
  The command "/var/www/..../gulp.sh" failed.
  Exit Code: 127 (Command not found)
  Host Name: remoteserver
  ================
  bash: line 1: /var/www/..../gulp.sh: No such file or directory

Exception trace:
 () at phar:///usr/local/bin/dep/src/Ssh/Client.php:96
 Deployer\Ssh\Client->run() at phar:///usr/local/bin/dep/src/functions.php:296
 Deployer\run() at /var/www/teddybox/data/www/deploy.teddyshop.test.php:57
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:105
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:142
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:324
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:119
 require() at /usr/local/bin/dep:4

dev_gulp [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

### Output log if i use **ssh user@remoteserver "date"** in deployer
➤ Executing task dev_gulp
[remoteserver] > ssh user@remoteserver "date"
[remoteserver] < ssh multiplexing initialization
[remoteserver] < Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-109-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

Может быть обновлён 1 пакет.
0 обновлений касаются безопасности системы.

*** Требуется перезагрузка системы ***
You have new mail.

[remoteserver] < Host key verification failed.
PHP Warning:  pcntl_fork() has been disabled for security reasons in phar:///usr/local/bin/dep/src/Utility/Reporter.php on line 22

  [Deployer\Exception\RuntimeException (255)]
  The command "ssh user@remoteserver "date"" failed.
  Exit Code: 255 (Unknown error)
  Host Name: remoteserver
  ================
  Host key verification failed.

Exception trace:
 () at phar:///usr/local/bin/dep/src/Ssh/Client.php:96
 Deployer\Ssh\Client->run() at phar:///usr/local/bin/dep/src/functions.php:296
 Deployer\run() at /var/www/teddybox/data/www/deploy.teddyshop.test.php:58
 Deployer\Deployer::Deployer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/dep/src/Task/Task.php:105
 Deployer\Task\Task->run() at phar:///usr/local/bin/dep/src/Executor/SeriesExecutor.php:63
 Deployer\Executor\SeriesExecutor->run() at phar:///usr/local/bin/dep/src/Console/TaskCommand.php:142
 Deployer\Console\TaskCommand->execute() at phar:///usr/local/bin/dep/vendor/symfony/console/Command/Command.php:264
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:869
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/src/Console/Application.php:132
 Deployer\Console\Application->doRunCommand() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:223
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/dep/vendor/symfony/console/Application.php:130
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/dep/src/Deployer.php:324
 Deployer\Deployer::run() at phar:///usr/local/bin/dep/bin/dep:119
 require() at /usr/local/bin/dep:4

dev_gulp [-p|--parallel] [-l|--limit LIMIT] [--no-hooks] [--log LOG] [--roles ROLES] [--hosts HOSTS] [-o|--option OPTION] [--] [<stage>]

**Comment by antonmedv** [comment] 2018-01-26 11:11
bash: line 1: /var/www/..../gulp.sh: No such file or directory

**Comment by familyman-131** [comment] 2018-01-26 11:15
yup, i told about it in description
> it looks like ssh command on webserver in the deployer task, after connect to remote server triyng to start script on webserver again, not command in .sh script

**Comment by antonmedv** [comment] 2018-01-26 11:20
So, it's not a bug then. Closing issue.

**Closed by antonmedv** 2018-01-26 11:20 UTC

**Comment by familyman-131** [comment] 2018-01-26 11:25
srsly, i try to do some command on remote server with .sh script in deployer task, deployer connects, and try to run not commands in script, but local script again, and it's OK?

**Comment by antonmedv** [comment] 2018-01-26 11:30
Ok what?

**Comment by familyman-131** [comment] 2018-01-26 11:34
you told it's not a bug ))
but why if i do task gulp.sh - deployer connects to remoteserver and says

>  bash: line 1: /var/www/..../gulp.sh: No such file or directory

it must reply something like 

> Птн Янв 26 11:34:23 EET 2018

am i wrong?
```bash content of gulp.sh
#!/bin/bash
/usr/bin/ssh user@remoteserver 'date'
```

**Comment by antonmedv** [comment] 2018-01-26 12:14
> No such file or directory

Check it.

**Comment by familyman-131** [comment] 2018-01-26 12:23
serv1 - webserver
deployer installed, task "dev_gulp" - described in first message
gulp.sh with "date" - content in first message
bash - exist

serv2 - remoteserver
bash - exist

i execute task dev_gulp on serv1 and i expect  "Птн Янв 26 11:34:23 EET 2018" output from serv2
but i get "bash: line 1: /var/www/..../gulp.sh: No such file or directory" AFTER connect to serv2
there is no scripts on serv2 calling in gulp.sh
just "ssh user@remoteserver 'date'"

if i just run on serv1 ./gulp.sh without deployer, i get expected "Птн Янв 26 11:34:23 EET 2018" output from serv2

so it must be my mistake or deployer bug

**Comment by antonmedv** [comment] 2018-01-26 12:56
Try to run dep with `-vvv` to see what's going on.

**Comment by familyman-131** [comment] 2018-01-26 13:01
The logs in first message, result of "dep -vvv" output.

**Comment by antonmedv** [comment] 2018-01-26 13:29
Check file exists.

**Comment by familyman-131** [comment] 2018-01-26 13:53
It exists, please check first 4 lines of "Output log if i use .sh in deployer"in first message

**Comment by antonmedv** [comment] 2018-01-26 15:54
> It exists, please check first 4 lines of "Output log if i use .sh in deployer"in first message

So no bug?

**Comment by familyman-131** [comment] 2018-01-27 08:25
I give up ))
it takes 5 minutes to reproduce situation in [this](https://github.com/deployphp/deployer/issues/1523#issuecomment-360771476) comment
i'm already accomplished my task in another way
anyway thanks a lot for a quick reply!
have a nice day!

**Comment by familyman-131** [comment] 2018-01-27 09:13
i've got it!
it was my mistake
i should add a "localhost" host in deploy.php
and run `dep task localhost -vvv`
this time all works as expected!
**not a bug**
