### ISSUE TITLE
Git error when deploying on Deployer 7.2.1

### ISSUE THREAD

**Issue by thinkcube-solutions** [deployphp/deployer#3537] opened 2023-03-10 23:51 UTC
- Deployer version: 7.2.1
- Deployment OS: MacOS Ventura 13.2.1

Running dep deploy stage=staging returns the following error from default **deploy:update_code** on a fresh common recipe. There is an error with the git clone process.

``` bash
[deployer]  error  in update_code.php on line 90:
[deployer] run export GIT_TERMINAL_PROMPT='0' GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=accept-new'; [ -f /var/www/deployer-7-testing/.dep/repo/HEAD ] || /usr/bin/git clone --mirror git@github.com:thinkcube-solutions/deployer-7-testing.git /var/www/deployer-7-testing/.dep/repo 2>&1
[deployer] err bash: line 1: syntax error near unexpected token `$'B\E[m/usr/bin/git''
[deployer] err bash: line 1: `( export GIT_TERMINAL_PROMPT='0' GIT_SSH_COMMAND='ssh -o StrictHostKeyChecking=accept-new'; [ -f /var/www/deployer-7-testing/.dep/repo/HEAD ] || /usr/bin/git clone --mirror git@github.com:thinkcube-solutions/deployer-7-testing.git /var/www/deployer-7-testing/.dep/repo 2>&1 ); printf '[exit_code:%s]' $?;'
[deployer]
[deployer] exit code -1 (Unknown error)
```

Deployer Config
``` php
<?php
namespace Deployer;

require 'recipe/common.php';

// Config

set('repository', 'git@github.com:thinkcube-solutions/deployer-7-testing.git');

// Allocate tty for git clone.
set('git_tty', true);

// Maximum amount of releases to keep on the remote server
set('keep_releases', 3);

// Writable directories by web server
set('writable_dirs', []);

// Set writeable mode to ACL
set('writable_mode', 'acl');

add('shared_files', []);
add('shared_dirs', []);
add('writable_dirs', []);

// Hosts

host('deployer')
    ->set('labels', ['stage' => 'staging'])
    ->set('branch', 'main')
    ->set('remote_user', 'deployer')
    ->set('deploy_path', '/var/www/deployer-7-testing');

// Tasks
desc('Update Deployer Permissions');
task('deploy:permissions:deployer', function() {
  run('sudo chown -R deployer:deployer {{deploy_path}}');
});

desc('Deploy your project');
task('deploy', [
  'deploy:permissions:deployer',
  'deploy:info',
  'deploy:prepare',
  'deploy:lock',
  'deploy:symlink',
  'deploy:unlock',
  'deploy:cleanup',
]);

// Hooks
after('deploy:failed', 'deploy:unlock');

```

I also had to setup a deploy:permissions:deployer task to update permissions otherwise the dep.lock file cannot be written to. I appreciate any advice, thank you!

**Comment by antonmedv** [comment] 2023-03-11 13:05
Duplicate of https://github.com/deployphp/deployer/discussions/3536

**Closed by antonmedv** 2023-03-11 13:05 UTC
