### ISSUE TITLE
[5.x] Deploy doesn't continue the first time

### ISSUE THREAD

**Issue by barryvdh** [deployphp/deployer#1192] opened 2017-05-01 21:35 UTC
| Q                 | A
| ----------------- | ---
| Issue Type        | Bug
| Deployer Version  | 5.0-beta2
| Local Machine OS  | CentOS
| Remote Machine OS | Ubuntu

### Description 
When starting deployment, it asks for my passprase but does not seem to continue. When doing `-vvv` it continues to deploy:lock within 1 second. 

Not sure how to debug this properly, because -vvv does work..

**Comment by antonmedv** [comment] 2017-05-02 06:44
I think it asking you password, but without prompt. Can you try to type your password?

**Comment by barryvdh** [comment] 2017-05-02 07:45
It seemed to take a long time and then ask for a password again and again
![screen shot 2017-05-02 at 09 43 40](https://cloud.githubusercontent.com/assets/973269/25608629/ef00974a-2f1b-11e7-88e5-f9354b83dbf7.png)

For some reason, after a few tries it DID started working, so not sure what is actually causing it. But I've had if for a few times, where running -vvv fixed it immediatly

**Comment by antonmedv** [comment] 2017-05-02 08:36
Really strange. I can't reproduce it.

**Comment by barryvdh** [comment] 2017-05-03 12:04
I think this might be related to issues with https://github.com/deployphp/deployer/issues/1187 only being swallowed.

**Comment by barryvdh** [comment] 2017-05-08 09:24
Still having a hard time debugging this, it seems to stall on the first try, but killing it and restarting, seems to do the trick. I don't have ssh-agent running so perhaps it doesn't work when asking the passphrase?

**Comment by antonmedv** [comment] 2017-05-08 09:32
It should work with passphrase as well. Tested by myself many times. Please, debug with this:
```php
host(...)
    ->addSshFlag('-vvvv')
```

**Comment by barryvdh** [comment] 2017-05-08 09:52
It seems to hang for a while and then ask for a passphrase in the background. After that it fails. (Running again doesn't ask for passphrase and runs correctly)

Log from `-vvvv` (note that running the second time with this flag also doesn't seem to work):
https://gist.github.com/barryvdh/3276182067403275cfc33ee70a342be5

**Comment by barryvdh** [comment] 2017-05-08 15:11
This is without that flag, but with `-vvv`;  

First time, hangs here
```
Executing task deploy:prepare
[95.85.xx.xx] > echo $0
[95.85.xx.xx] < ssh multiplexing initialization
Enter passphrase for key '/home/projects/.ssh/id_rsa':
[95.85.xx.xx] < bash
```

Right after again:
```
➤ Executing task deploy:prepare
[95.85.xx.xx] > echo $0
[95.85.xx.xx] < bash
[95.85.xx.xx] > if [ ! -d /home/forge/default ]; then mkdir -p /home/forge/default; fi
```

**Comment by barryvdh** [comment] 2017-05-08 15:15
So it looks the 2nd attempt uses the multiplex from the first attempt correctly. Only the first attempt itself can't.

**Comment by antonmedv** [comment] 2017-05-08 17:18
This works correctly? `Enter passphrase for key '/home/projects/.ssh/id_rsa':`

Also check it with ssh agent is running.

**Comment by barryvdh** [comment] 2017-05-08 17:43
Entering the key works indeed. When I disable multiplexing, it asks the passphrase for each command though (so like 8 times for prepare).

```
➤ Executing task deploy:prepare
Enter passphrase for key '/home/projects/.ssh/id_rsa': 
Enter passphrase for key '/home/projects/.ssh/id_rsa': 
Enter passphrase for key '/home/projects/.ssh/id_rsa': 
Enter passphrase for key '/home/projects/.ssh/id_rsa': 
Enter passphrase for key '/home/projects/.ssh/id_rsa': 
✔nter passphrase for key '/home/projects/.ssh/id_rsa': 
➤ Executing task deploy:release
Enter passphrase for key '/home/projects/.ssh/id_rsa': 
```

Will try with ssh-agent in a few minutes (can't try now because it works soon after)

**Comment by barryvdh** [comment] 2017-05-08 18:20
With ssh-agent, same issue only it doesn't ask for passphrase.

**Comment by antonmedv** [comment] 2017-05-09 01:25
It should not ask passphrase with ssh agent. That's agent for. =)

**Comment by antonmedv** [comment] 2017-05-10 14:02
Please, check master branch. I think i fixed it 😄  7c312bfe82e11745e1be082f586b92927f88dedc

**Comment by barryvdh** [comment] 2017-05-10 14:13
Do you happen to have a .phar? (Might be cool to have automatic/nightly phars?)

**Comment by barryvdh** [comment] 2017-05-10 14:47
Same issue when running from source :(

**Comment by barryvdh** [comment] 2017-05-15 12:41
FYI, same behavior with the final 5.0.0

**Comment by antonmedv** [comment] 2017-05-15 12:47
Can't reproduce. Can you give me remote access to your machine to debug?

**Comment by barryvdh** [comment] 2017-05-15 12:52
Not easily. I'll see if I can reproduce on different systems. Currently using Centos 6.6

**Comment by harisenbon** [comment] 2017-05-18 00:25
I'm having the same issue.
I thought that it was freezing, but it actually seems to just be taking a long time to run.
I left the process running in the background, and about 10 minutes later deploy:prepare completed.

When using -vv or -vvv flags, tasks run at a reasonable pace.

Have tried this with both the latest phar as well as composer.
Running on MacOSX with PHP 7.0.18

**Comment by antonmedv** [comment] 2017-05-18 01:11
@harisenbon can i try to debug it through teamviewerr?

**Comment by harisenbon** [comment] 2017-05-18 14:34
@antonmedv how about a zoom call? I can give you access with that and we can walk through it.
What's the best way to send you an invite?

**Comment by barryvdh** [comment] 2017-05-18 15:11
I increased the sleep(1) to sleep(10), which gives me the time to enter the passphrase.

What is happening is this:

 - Starting process `ssh -M $sshArguments $host` without waiting for response
 - sleep is called, waiting
 - continue with program

When the popup comes for the passphrase, this takes more then 1 second, so the order becomes this:

 - Starting process
 - Passphrase is asked
 - sleep starts
 - sleep ends
 - continue with program
 - passphrase is entered, multiplex is initialized (too late)

Next time, it still used the multiplex from the first try.

**Comment by barryvdh** [comment] 2017-05-18 16:21
Okay, what do you think of https://github.com/deployphp/deployer/pull/1220

I used the first check after the multiplexing command. If it's still not running, keep trying for 60 secs, the throw an exception. This seems to work for me. When you don't pay attention, it will show a more clear error after 60 secs, but otherwise it will continue after max 1 sec after the password

**Comment by antonmedv** [comment] 2017-05-18 17:30
Merged. Thanks for solution.

**Closed by antonmedv** 2017-05-18 17:30 UTC
Labels: bug
