### ISSUE TITLE
How to deploy via rsync or copy?

### ISSUE THREAD

**Issue by geevcookie** [deployphp/deployer#60] opened 2014-09-02 18:40 UTC
On your website you make the following statement:
Deploy your code to all servers you want, it supports deploy via copy, or via VCS (like git), or via rsync.

However, I am unable to see how exactly one would deploy via "copy" or rsync. It is unclear from the documentation or from the source code.

Could you please give an example deploy.php file showing how this can be done? Or does one have to write the custom tasks running all the appropriate rsync or "copy" commands?

**Comment by Flyingmana** [comment] 2015-02-05 21:03
I will take over this issue, already have working code for deploy via "copy" only need to refactor it a bit.

**Comment by elfet** [comment] 2015-02-24 15:12
It will be in docs.

You can override `deploy:update_code` task.

**Comment by gpupo** [comment] 2015-05-22 17:40
I can see this documentation?

**Comment by johnny-bit** [comment] 2015-06-08 20:39
I've tried to do it today and it's problematic. First of all: we can't get user for server so - no way to specify user for remote host, instead have to define user twice.

overriding update_code is only part-measure if You want to have proper cpy/rsync operations.

First You have to prepare local release path, then override vendors or other taks that installs deps to remote and finally rsync everything
At first I was tempted to use upload from functions.php, however it does not allow You to set some fine grained includes/excludes so that left me with rsync ran locally to remote + double defining user.

Want to have a look at my recipe? or shall I PR that stuff? or both ;)

**Comment by elfet** [comment] 2015-06-09 01:41
Can you open PR for this? As separate recipe?

**Comment by johnny-bit** [comment] 2015-06-09 06:55
Sure :smiling_imp: Let me just clear code and I'll PR it against deployphp/recipes

**Comment by ZeeCoder** [comment] 2015-06-09 07:00
:+1:

**Comment by johnny-bit** [comment] 2015-06-10 15:22
I've added a PR for this and stripped helluva lots of our own special-purpose code... Looks ok on our end and I hope it's ok for others :smiling_imp:

**Comment by johnny-bit** [comment] 2015-06-11 17:52
Now that rsync recipe is in IMO nice shape I wanted to ask everybody about deployment strategies that would use rsync and some of my ideas that would speed up my PR-ed recipe very nicely.

** My work flow **

So - my work flow and rationale for it is caused by one common thing: Most of our customers use shared hosting on which there's no git, no sudo capabilities, installing composer is nightmarish and you can completely forget about Node-based stuff like gulp or bower.

After getting Deployer to work nicely and rsync everything, the work flow I'm enjoying right now is this:

* Work on development machine and preview suff locally 
* Rsync stuff to dev-preview hosting. (that is handled via deployer. I could add tiny tasks to PR if anyone is interested in rsyncing from devel dir instead of building everything everytime in temporary dir)
* Deploy to staging machine where we can run everything. This is mostly very nice and very typical deploy where everything is on remote. (In capifony it was "deployment -> scm -> production" )
* And finally the use-case from my recipe: get code from scm locally (temporary), run all compile-like things locally, push compiled release and dist-files via rsync to production. (so this is "deployment -> production")

One thing that could speed up my recipe is to copy everything from last release instead of creating new folder and then rsync to new release dir. In most cases (obviously depending on what is deployed) that move could result in huge speedup, because then rsync could work like rsync should - sending only changes.

**Comment by elfet** [comment] 2015-06-12 05:28
@johnny-bit this is good work flow. But i think it's better to decouple rsync tasks/recipe from others. 
A lot of people will be using just rsync tasks with standard workflow (sudo, ACL, composer, bower on server) and for then will be god to has separate rsync recipe.
Otherwise, your shared-hosting workflow it's too very common and it will be grate has separate recipe to this workflow too!

**Comment by johnny-bit** [comment] 2015-06-18 06:37
Ok, to sum up recent PRs to recipes repo: There's two separate recipes: 
One is `local` that one can use as basis for local clone strategy. For simple copy deploy one can take local clone and using `upload` function, copy it to server. (if I understood correctly the whole point of copy deploy ;) )
Second is `rsync` that allows one to rsync anything from local to remote. Combining `local` and `rsync` gives one perfect local-copy&rsync.
Those two recipes also cover shared hosting woes where one can hardly do anything except log into server and do some basic commands.

Only problem I see: it's hard to see thisconnection in docs. Maybe we could whip out some examples?

**Closed** 2015-08-21 07:33 UTC
Labels: feature

**Comment by webdevilopers** [comment] 2015-11-13 08:02
What is the current state of the `copy` task? Could you please link the PR you mentioned @johnny-bit ?
Thanks!

**Comment by johnny-bit** [comment] 2015-11-13 08:20
@webdevilopers look into deployphp/recipes, there you'll find 'rsync' recipe as well as 'local' recipe. The docs also help a lot.

**Comment by webdevilopers** [comment] 2015-11-13 08:25
Thanks @johnny-bit . I looked at https://github.com/deployphp/recipes/blob/master/docs/local.md and not sure if this solves my use case.

Instead of pulling a git clone on my target remote server I have to clone it locally because git has to be behind our firewall. Magallanes / MagePHP featured a tar archive that could then be pushed to remote. It would then be unzipped and handled there.

Do you think this is covered or am i looking for a different task / recipe?

Thanks in advance!

**Comment by johnny-bit** [comment] 2015-11-13 08:29
Well, no. There's no such feature now. My approach with local and rsync
recipes was to use local to compile suff locally, then rsync it to remote,
since rsyncing is waaay faster than uploading ~3GB worth of compiled data
every dam time. Even with tar/zip archives that would take considerable
amount of data to be uploaded.

Currently, if You would like it this way, you could use local recipe to
compile locally, then wirte task to create archive an then use upload
function out of deployer and viola :)

2015-11-13 9:25 GMT+01:00 webDEVILopers <notifications@github.com>:

> Thanks @johnny-bit <https://github.com/johnny-bit> . I looked at
> https://github.com/deployphp/recipes/blob/master/docs/local.md and not
> sure if this solves my use case.
>
> Instead of pulling a git clone on my target remote server I have to clone
> it locally because git has to be behind our firewall. Magallanes / MagePHP
> featured a tar archive that could then be pushed to remote. It would then
> be unzipped and handled there.
>
> Do you think this is covered or am i looking for a different task / recipe?
>
> Thanks in advance!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployphp/deployer/issues/60#issuecomment-156360609>.
>



-- 
Pozdrawiam,
Hubert Kowalski

**Comment by webdevilopers** [comment] 2015-11-13 08:31
Thanks for the comment @johnny-bit ! Clear to me now!

Maybe I will have to convince my guys to make the GIT accessible by the remote anyway! ;)

**Comment by johnny-bit** [comment] 2015-11-13 09:03
The only reason i did local and rsync is because I work with customers that
have hosting on shared environments... and i'm still pondering whether to
do ftp recipe or not since i also have cheapasses that get cheapest hosting
without even ssh access:)

convince guys to allow git accessible byremote, since git can authorize via
ssh an publickeys if needed :) it's easier that way.

2015-11-13 9:31 GMT+01:00 webDEVILopers <notifications@github.com>:

> Thanks for the comment @johnny-bit <https://github.com/johnny-bit> !
> Clear to me now!
>
> Maybe I will have to convince my guys to make the GIT accessible by the
> remote anyway! ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deployphp/deployer/issues/60#issuecomment-156361367>.
>



-- 
Pozdrawiam,
Hubert Kowalski
